[package]
name = "scorer"
version.workspace = true
edition.workspace = true
rust-version.workspace = true
authors.workspace = true
license.workspace = true
repository.workspace = true
description = "Temporal Weighted Health Score algorithm"

[dependencies]
serde.workspace = true
time.workspace = true
thiserror.workspace = true
anyhow.workspace = true

[dev-dependencies]
time = { workspace = true, features = ["macros"] }

[lints]
workspace = true
